title: My awesome title
email: your-email@example.com
description:
  some description
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: daigo.hirooka
github_username:  daigo0927

# Build settings
sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
  - {scope: {type: posts}, values: {layout: post, permalink: '/:categories/:title'}}
    
include:
  - _pages

exclude:
  - CNAME
  - README.md
  - format.md
  - Gemfile
  - Gemfile.lock
  - vendor
  
paginate: 3
paginate_path: '/:num'

theme: jekyll-theme-cayman